import {
  Leaf,
  Dumbbell,
  Wine,
  Users,
  Zap,
  Wifi,
  ParkingCircle,
  Shield,
  Waves,
  Sunset,
  Sparkles,
  Laptop,
  Film,
  Baby,
  Building2,
  Car,
  Package,
  PawPrint,
  Flame,
  Shirt,
  BookOpen,
  Coffee,
  Briefcase,
  Maximize2,
  Smartphone,
  Gamepad2,
  type LucideIcon,
} from "lucide-react";

export const AMENITY_ICON_MAP: Record<string, LucideIcon> = {
  leaf: Leaf,
  dumbbell: Dumbbell,
  wine: Wine,
  users: Users,
  zap: Zap,
  wifi: Wifi,
  "parking-circle": ParkingCircle,
  shield: Shield,
  waves: Waves,
  sunset: Sunset,
  sparkles: Sparkles,
  laptop: Laptop,
  film: Film,
  baby: Baby,
  "building-2": Building2,
  car: Car,
  package: Package,
  "paw-print": PawPrint,
  "shield-check": Shield,
  flame: Flame,
  shirt: Shirt,
  "book-open": BookOpen,
  coffee: Coffee,
  briefcase: Briefcase,
  "maximize-2": Maximize2,
  smartphone: Smartphone,
  "gamepad-2": Gamepad2,
};

export function getAmenityIcon(name: string | null | undefined): LucideIcon {
  return (name ? AMENITY_ICON_MAP[name] : null) ?? Sparkles;
}
